name: first_workflow
on: workflow_dispatch 
jobs: 
   Nighthawk: 
     runs-on: ubuntu-latest
     steps: 
       - name: Hello world 
         run: echo " Hello World! " 
       - name: Bye
         run: echo " Bye "
